routes/web.php
<?php


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\BiodataController;
use App\Http\Controllers\DepartemenController;
use App\Http\Controllers\KaryawanController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\EvaluasiController;
use App\Http\Controllers\FileManagerController;

Route::get('/', function () {
    return view('index');
});

Auth::routes();
Route::group(['middleware' => ['auth']], function () {
    //CRUD Departemen
    Route::resource('departemen', DepartemenController::class);
    //CRUD Karyawan
    Route::resource('karyawan', KaryawanController::class);
    //CRUD Profile
    Route::resource('profile', ProfileController::class);
    //CRUD Laporan
    Route::resource('laporan', LaporanController::class);
    //CRUD Evaluasi
    Route::resource('evaluasi', EvaluasiController::class);
    //CRUD Biodata
    Route::get('/karyawan/{id}/create-bio', [BiodataController::class, "create"]);
    Route::post('/karyawan/{id}', [BiodataController::class, "store"]);
    Route::get('/karyawan/{id}/edit-bio', [BiodataController::class, "edit"]);
    Route::put('/karyawan/{id}', [BiodataController::class, "update"]);
    // File Manager
    Route::get('/file-manager', [FileManagerController::class, 'index'])->name('file-manager');
    Route::post('/upload', [FileManagerController::class, 'upload'])->name('upload');
    Route::delete('/delete/{filename}', [FileManagerController::class, 'delete'])->name('delete');
});

app/Models/Laporan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Laporan extends Model
{
    protected $table = 'laporan_evaluasi';
    protected $fillable = [
        'karyawan_id', 'tanggal', 'isi_laporan', 'jenis_laporan'
    ];

    public function karyawan()
    {
        return $this->belongsTo(Karyawan::class, 'karyawan_id');
    }
}

app/Http/Controllers/LaporanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Laporan;
use App\Models\Karyawan;
use Barryvdh\DomPDF\Facade\Pdf;

class LaporanController extends Controller
{
    public function index()
    {
        $laporan = Laporan::all()->keyBy('id');
        $title = 'Hapus Laporan!';
        $text = "Apakah anda yakin ingin menghapus entry ini?";
        confirmDelete($title, $text);
        return view('laporan.index', compact('laporan'));
    }

    public function create()
    {
        $laporan = Laporan::all();
        $karyawan = Karyawan::all();
        return view('laporan.create', compact('laporan', 'karyawan'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'karyawan_id' => 'required',
            'tanggal' => 'required',
            'isi_laporan' => 'required',
            'jenis_laporan' => 'required',
        ]);

        $laporan = Laporan::create([
            'karyawan_id' => $request->karyawan_id,
            'tanggal' => $request->tanggal,
            'isi_laporan' => $request->isi_laporan,
            'jenis_laporan' => $request->jenis_laporan,
        ]);

        $pdf = Pdf::loadView('pdf.invoice', compact('laporan'));
        $pdf->save(resource_path('filespdf/' . $laporan->id . '.pdf'));

        return redirect('/laporan')->with('success', 'Laporan berhasil ditambahkan.');
    }

    public function show($id)
    {
        $laporan = Laporan::find($id);
        return view('laporan.detail', compact('laporan'));
    }

    public function edit($id)
    {
        $laporan = Laporan::find($id);
        $karyawan = Karyawan::all();
        return view('laporan.edit', compact('laporan', 'karyawan'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'karyawan_id' => 'required',
            'tanggal' => 'required',
            'isi_laporan' => 'required',
            'jenis_laporan' => 'required',
        ]);

        $laporan = Laporan::find($id);
        $laporan->karyawan_id = $request->karyawan_id;
        $laporan->tanggal = $request->tanggal;
        $laporan->isi_laporan = $request->isi_laporan;
        $laporan->jenis_laporan = $request->jenis_laporan;
        $laporan->save();

        return redirect('/laporan')->with('success', 'Laporan berhasil diperbarui.');
    }


    public function destroy($id)
    {
        $laporan = Laporan::find($id);
        $laporan->delete();

        return redirect('/laporan')->with('success', 'Laporan berhasil dihapus.');
    }
}

resources/views/laporan/create.blade.php
@extends('layouts.master')

@section('tab-title', 'Demo Sistem Manajemen || Laporan')
@section('title', 'Tambah Laporan')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <form action="{{ url('/laporan') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label for="nama">Nama:</label>
                        <select name="karyawan_id" class="form-control @error('karyawan_id') is-invalid @enderror">
                            <option value="">--Pilih Karyawan--</option>
                            @forelse ($karyawan as $person)
                                <option value="{{ $person->id }}">{{ $person->name }}</option>
                            @empty
                                <option value="">Tidak Ada Karyawan</option>
                            @endforelse
                        </select>
                    </div><br>
                    <div class="form-group">
                        <label for="tanggal">Tanggal:</label>
                        <input type="date" name="tanggal" class="form-control">
                    </div><br>
                    <div class="form-group">
                        <label for="isi_laporan">Isi Laporan:</label>
                        <textarea name="isi_laporan" class="form-control" rows="5" placeholder="Silakan tuliskan isi laporan di sini..."></textarea>
                        <small id="isi_laporan_help" class="form-text text-muted">Tulis laporan dengan jelas dan rinci agar
                            dapat dipahami oleh pihak terkait.</small>
                    </div><br>
                    <div class="form-group">
                        <label for="jenis_laporan">Jenis Laporan:</label>
                        <input type="text" name="jenis_laporan" class="form-control">
                    </div><br>
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/laporan/detail.blade.php
@extends('layouts.master')

@section('tab-title', 'Demo Sistem Manajemen')
@section('title', 'Detail Laporan')

@section('content')
    <div class="mt-3">
        <div>
            <strong>Nama:</strong> {{ $laporan->karyawan->nama }} <br>
            <strong>Tanggal:</strong> {{ $laporan->tanggal }} <br>
            <strong>Isi Laporan:</strong> {{ $laporan->isi_laporan }} <br>
            <strong>Jenis Laporan:</strong> {{ $laporan->jenis_laporan }} <br>
        </div>
    </div><br>
    <a href="{{ url('/laporan') }}" class="btn btn-secondary">Kembali</a>
@endsection

resources/views/laporan/edit.blade.php
@extends('layouts.master')

@section('tab-title', 'Demo Sistem Manajemen || Laporan')
@section('title', 'Edit Laporan')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <form action="{{ route('laporan.update', $laporan->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="nama">Nama:</label>
                        <select name="karyawan_id" class="form-control @error('karyawan_id') is-invalid @enderror">
                            <option value="">--Pilih Karyawan--</option>
                            @forelse ($karyawan as $person)
                                <option value="{{ $person->id }}"
                                    {{ $person->id == $laporan->karyawan_id ? 'selected' : '' }}>{{ $person->name }}
                                </option>
                            @empty
                                <option value="">Tidak Ada Karyawan</option>
                            @endforelse
                        </select>
                    </div><br>
                    <div class="form-group">
                        <label for="tanggal">Tanggal:</label>
                        <input type="date" name="tanggal" class="form-control" value="{{ $laporan->tanggal }}">
                    </div><br>
                    <div class="form-group">
                        <label for="isi_laporan">Isi Laporan:</label>
                        <textarea name="isi_laporan" class="form-control" rows="5">{{ $laporan->isi_laporan }}</textarea>
                    </div><br>
                    <div class="form-group">
                        <label for="jenis_laporan">Jenis Laporan:</label>
                        <input type="text" name="jenis_laporan" class="form-control"
                            value="{{ $laporan->jenis_laporan }}">
                    </div><br>
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/laporan/index.blade.php
@extends('layouts.master')

@section('tab-title', 'Demo Sistem Manajemen || Laporan')
@section('title', 'Laporan')

@section('content')
    <div class="row">
        <div class="col-12 col-lg-12 col-xxl-9 d-flex">
            <div class="card flex-fill">
                <div class="card-header">
                    <a href="{{ url('/laporan/create') }}" class="btn btn-primary">Tambah Laporan</a>
                </div>
                <table class="table table-hover my-0">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Nama</th>
                            <th class="d-none d-xl-table-cell">Tanggal</th>
                            <th class="d-none d-md-table-cell">Laporan</th>
                            <th class="d-none d-md-table-cell">Jenis Laporan</th>
                            <th class="d-none d-md-table-cell">Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($laporan as $index => $lap)
                            <tr>
                                <td>{{ $index }}</td>
                                <td class="d-none d-md-table-cell">{{ $lap->karyawan->name }}</td>
                                <td class="d-none d-xl-table-cell">{{ $lap->tanggal }}</td>
                                <td>{{ $lap->isi_laporan }}</td>
                                <td>{{ $lap->jenis_laporan }}</td>
                                <td>
                                    <a href="{{ url('/laporan/' . $lap->id) }}" class="btn btn-info btn-sm">Detail</a>
                                    <a href="{{ url('/laporan/' . $lap->id . '/edit') }}"
                                        class="btn btn-warning btn-sm">Edit</a>
                                    <form action="{{ url('/laporan/' . $lap->id) }}" method="POST" style="display:inline;">
                                        @csrf
                                        @method('DELETE')
                                        <a href="{{ url('/laporan/' . $lap->id) }}" class="btn btn-danger btn-sm" data-confirm-delete="true">Hapus</a>
                                        {{-- <button type="submit" class="btn btn-danger btn-sm"
                                            onclick="return confirm('Yakin ingin menghapus?')">Hapus</button> --}}
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection