routes/web.php
<?php


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\BiodataController;
use App\Http\Controllers\DepartemenController;
use App\Http\Controllers\KaryawanController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\EvaluasiController;
use App\Http\Controllers\FileManagerController;

Route::get('/', function () {
    return view('index');
});

Auth::routes();
Route::group(['middleware' => ['auth']], function () {
    //CRUD Departemen
    Route::resource('departemen', DepartemenController::class);
    //CRUD Karyawan
    Route::resource('karyawan', KaryawanController::class);
    //CRUD Profile
    Route::resource('profile', ProfileController::class);
    //CRUD Laporan
    Route::resource('laporan', LaporanController::class);
    //CRUD Evaluasi
    Route::resource('evaluasi', EvaluasiController::class);
    //CRUD Biodata
    Route::get('/karyawan/{id}/create-bio', [BiodataController::class, "create"]);
    Route::post('/karyawan/{id}', [BiodataController::class, "store"]);
    Route::get('/karyawan/{id}/edit-bio', [BiodataController::class, "edit"]);
    Route::put('/karyawan/{id}', [BiodataController::class, "update"]);
    // File Manager
    Route::get('/file-manager', [FileManagerController::class, 'index'])->name('file-manager');
    Route::post('/upload', [FileManagerController::class, 'upload'])->name('upload');
    Route::delete('/delete/{filename}', [FileManagerController::class, 'delete'])->name('delete');
});

app/Models/Evaluasi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Evaluasi extends Model
{
    protected $table = 'kpi';
    protected $fillable = [
        'karyawan_id', 'laporan_evaluasi_id', 'value'
    ];

    public function karyawan()
    {
        return $this->belongsTo(Karyawan::class, 'karyawan_id');
    }

    public function laporanEvaluasi()
    {
        return $this->belongsTo(Laporan::class, 'laporan_evaluasi_id');
    }
}

app/Http/Controllers/EvaluasiController.php
<?php

namespace App\Http\Controllers;

use App\Models\Evaluasi;
use App\Models\Karyawan;
use App\Models\Laporan;
use Illuminate\Http\Request;

class EvaluasiController extends Controller
{
    public function index()
    {
        $evaluasi = Evaluasi::all();
        $title = 'Hapus Evaluasi!';
        $text = "Apakah anda yakin ingin menghapus entry ini?";
        confirmDelete($title, $text);
        return view('evaluasi.index', compact('evaluasi'));
    }

    public function create()
    {
        $karyawan = Karyawan::all();
        $laporan = Laporan::all();
        return view('evaluasi.create', compact('karyawan', 'laporan'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'karyawan_id' => 'required',
            'laporan_evaluasi_id' => 'required',
            'value' => 'required',
        ]);

        Evaluasi::create($request->all());

        return redirect('/evaluasi')->with('success', 'Evaluasi berhasil ditambahkan.');
    }

    public function show($id)
    {
        $evaluasi = Evaluasi::findOrFail($id);
        return view('evaluasi.detail', compact('evaluasi'));
    }

    public function edit($id)
    {
        $evaluasi = Evaluasi::findOrFail($id);
        $karyawan = Karyawan::all();
        $laporan = Laporan::all();
        return view('evaluasi.edit', compact('evaluasi', 'karyawan', 'laporan'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'karyawan_id' => 'required',
            'laporan_evaluasi_id' => 'required',
            'value' => 'required',
        ]);

        $evaluasi = Evaluasi::findOrFail($id);
        $evaluasi->update($request->all());

        return redirect('/evaluasi')->with('success', 'Evaluasi berhasil diperbarui.');
    }

    public function destroy($id)
    {
        $evaluasi = Evaluasi::findOrFail($id);
        $evaluasi->delete();

        return redirect('/evaluasi')->with('success', 'Evaluasi berhasil dihapus.');
    }
}

resources/views/evaluasi/create.blade.php
@extends('layouts.master')

@section('tab-title', 'Demo Sistem Manajemen || Evaluasi')
@section('title', 'Tambah Evaluasi')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <form method="POST" action="{{ route('evaluasi.store') }}">
                    @csrf

                    <div class="form-group">
                        <label for="nama">Karyawan:</label>
                        <select name="karyawan_id" id="karyawan_id"
                            class="form-control @error('karyawan_id') is-invalid @enderror">
                            <option value="">--Pilih Karyawan--</option>
                            @foreach ($karyawan as $person)
                                <option value="{{ $person->id }}">{{ $person->name }}</option>
                            @endforeach
                        </select>
                    </div><br>

                    <div class="form-group">
                        <label for="KPI">Laporan Evaluasi: </label>
                        <select name="laporan_evaluasi_id" class="form-control"
                            @error('laporan_evaluasi_id') is-invalid @enderror>
                            <option value="">--Pilih Laporan--</option>
                            @forelse ($laporan as $item)
                                <option value="{{ $item->id }}">{{ $item->isi_laporan }}</option>
                            @empty
                                <option value="">Tidak Ada Laporan</option>
                            @endforelse
                        </select>
                    </div><br>

                    <div class="form-group">
                        <label for="value">Nilai Evaluasi</label>
                        <input type="text" class="form-control" id="value" name="value">
                    </div><br>

                    <button type="submit" class="btn btn-primary">Simpan</button>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        // Fetch and populate laporan evaluasi based on selected karyawan
        document.getElementById('karyawan_id').addEventListener('change', function() {
            var karyawanId = this.value;
            var laporanSelect = document.getElementById('laporan_evaluasi_id');
            laporanSelect.innerHTML = ''; // Clear existing options

            if (karyawanId !== '') {
                // Make an AJAX request to fetch laporan evaluasi for the selected karyawan
                fetch('/api/laporan-evaluasi/' + karyawanId)
                    .then(response => response.json())
                    .then(data => {
                        data.forEach(laporan => {
                            var option = document.createElement('option');
                            option.value = laporan.id;
                            option.textContent = laporan.judul;
                            laporanSelect.appendChild(option);
                        });
                    });
            }
        });
    </script>
@endsection

resources/views/evaluasi/detail.blade.php
@extends('layouts.master')

@section('tab-title', 'Demo Sistem Manajemen')
@section('title', 'Detail Evaluasi')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h2>Detail Evaluasi</h2>
                <p><strong>Nama Karyawan:</strong> {{ $evaluasi->karyawan->name }}</p>
                <p><strong>Isi Laporan:</strong> {{ $evaluasi->laporanEvaluasi->isi_laporan }}</p>
                <p><strong>Nilai:</strong> {{ $evaluasi->value }}</p>
                <!-- You can add more details here if needed -->
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-8">
                <a href="{{ url('/evaluasi') }}" class="btn btn-secondary">Kembali</a>
            </div>
        </div>
    </div>
@endsection

resources/views/evaluasi/edit.blade.php
@extends('layouts.master')

@section('tab-title', 'Demo Sistem Manajemen || Evaluasi')
@section('title', 'Edit Evaluasi')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <form method="POST" action="{{ route('evaluasi.update', $evaluasi->id) }}">
                    @csrf
                    @method('PUT')

                    <div class="form-group">
                        <label for="nama">Karyawan:</label>
                        <select name="karyawan_id" id="karyawan_id"
                            class="form-control @error('karyawan_id') is-invalid @enderror">
                            <option value="">--Pilih Karyawan--</option>
                            @foreach ($karyawan as $item)
                                <option value="{{ $item->id }}"
                                    {{ $item->id == $item->karyawan_id ? 'selected' : '' }}>
                                    {{ $item->name }}
                                </option>
                            @endforeach
                        </select>
                    </div><br>

                    <div class="form-group">
                        <label for="KPI">Laporan Evaluasi: </label>
                        <select name="laporan_evaluasi_id" class="form-control"
                            @error('laporan_evaluasi_id') is-invalid @enderror>
                            <option value="">--Pilih Laporan--</option>
                            @foreach ($laporan as $item)
                                <option value="{{ $item->id }}"
                                    {{ $item->id == $evaluasi->laporan_evaluasi_id ? 'selected' : '' }}>
                                    {{ $item->isi_laporan }}
                                </option>
                            @endforeach
                        </select>
                    </div><br>

                    <div class="form-group">
                        <label for="value">Nilai Evaluasi</label>
                        <input type="text" class="form-control" id="value" name="value"
                            value="{{ $evaluasi->value }}">
                    </div><br>

                    <button type="submit" class="btn btn-primary">Simpan</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/evaluasi/index.blade.php
@extends('layouts.master')

@section('tab-title', 'Demo Sistem Manajemen || Evaluasi')
@section('title', 'Evaluasi')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card-header">
                    <a href="{{ url('/evaluasi/create') }}" class="btn btn-primary">Tambah Evaluasi</a>
                    <a href="{{ route('file-manager') }}" class="btn btn-secondary">File Manager</a>
                </div>
                <table class="table table-hover my-0">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th class="d-none d-xl-table-cell">Nama Karyawan</th>
                            <th class="d-none d-md-table-cell">Laporan</th>
                            <th class="d-none d-xl-table-cell">Nilai</th>
                            <th class="d-none d-md-table-cell">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($evaluasi as $index => $item)
                            <tr>
                                <td>{{ $index + 1 }}</td>
                                <td class="d-none d-md-table-cell">{{ $item->karyawan->name }}</td>
                                <td class="d-none d-xl-table-cell">
                                    <a href="{{ route('laporan.show', $item->laporanEvaluasi->id) }}">Lihat Laporan</a>
                                </td>
                                <td class="d-none d-xl-table-cell">{{ $item->value }}</td>
                                <td>
                                    <a href="{{ route('evaluasi.show', $item->id) }}" class="btn btn-info btn-sm">Detail</a>
                                    <a href="{{ route('evaluasi.edit', $item->id) }}"
                                        class="btn btn-warning btn-sm">Edit</a>
                                    <form action="{{ route('evaluasi.destroy', $item->id) }}" method="POST"
                                        style="display:inline;">
                                        @csrf
                                        @method('DELETE')
                                        <a href="{{ route('evaluasi.destroy', $item->id) }}" class="btn btn-danger btn-sm" data-confirm-delete="true">Hapus</a>
                                        {{-- <button type="button" class="btn btn-danger btn-sm swal-confirm"
                                            data-confirm-title="Delete Item"
                                            data-confirm-text="Are you sure you want to delete this item?">Delete</button> --}}
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection